### ISSUE TITLE
CSUN Logo Off-Centered

### ISSUE THREAD

**Issue by NimaShafie** [kyeou/CSUN-Dashboard#33]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/69773301/234395114-95f984c0-cbe5-4e33-88f8-c91f02c10ff8.png">

<img width="99" alt="image" src="https://user-images.githubusercontent.com/69773301/234395071-e532c31a-de0e-434a-a95c-0e17f2e1c20e.png">

CSUN Logo is not centered correctly

**Comment by NimaShafie** [comment]
Changed via commits:
556397b627f1d9817cfc6e7a05133f8280de26c7 mine
620a77c1b0369d1ab080061255acaeacccc81bbb christians

Looks like there some cross platform incapabilites

**Comment by kyeou** [comment]
i found out what caused this
I made the logo a <li> element rather than a div, so the bullet point that <li> creates knocked it a couple pixels down the viewport
